# $(npm bin)/antora --clean --fetch antora-playbook.yml
site:
  title: Couchbase Docs Sandbox
  url: https://docs-sandbox.couchbase.com
  start_page: cloud::index.adoc
  robots: disallow
git:
  ensure_git_suffix: false
content:
  # NOTE the git@ segment in the URL indicates which repositories are private
  sources:
  - url: https://git@github.com/couchbaselabs/project-avengers
    branches: master
    start_path: docs/public
  - url: https://git@github.com/couchbase/couchbase-operator
    branches: [2.0.x]
    start_path: docs/user
asciidoc:
  attributes:
    max-include-depth: 10
    page-partial: false
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    xrefstyle: short
    enterprise: https://www.couchbase.com/products/editions[ENTERPRISE EDITION]
    community: https://www.couchbase.com/products/editions[COMMUNITY EDITION]
  extensions:
  - ./lib/json-config-ui-block-macro.js
  - ./lib/inline-man-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui-sandbox/releases/download/cloud-3/ui-bundle.zip
output:
  dir: ./public
