[build]
  base = "netlify/"
  publish = "public/"
  command = "git checkout -B $BRANCH && sed -i \"s;git@github.com:;https://$GITHUB_TOKEN:x-oauth-basic@github.com/;g\" ../site.yml && node_modules/.bin/antora --url https://docs-staging.couchbase.com --pull --redirect-facility=netlify ../site.yml && sed -i \"s;^/index.html ;/ ;\" ../public/_redirects"

[build.environment]
  NODE_VERSION = "8"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.production.environment]
  ALGOLIA_APP_ID = "E80Q5UHPOS"
  ALGOLIA_API_KEY = "6e7248a6d21038512a92145e9b903757"
  ALGOLIA_INDEX_NAME = "couchbase-docs-next"
  FEEDBACK_BUTTON = "true"

[context.deploy-preview]
  command = "git checkout -B $BRANCH && sed -i \"s;git@github.com:;https://$GITHUB_TOKEN:x-oauth-basic@github.com/;g\" ../site.yml && node_modules/.bin/antora --url $DEPLOY_PRIME_URL --pull --redirect-facility=netlify ../site.yml && sed -i \"s;^/index.html ;/ ;\" ../public/_redirects"

[[headers]]
  for = "/_/font/*"
  [headers.values]
    Cache-Control = "public,max-age=604800"
