[build]
base = "netlify/"
publish = "public/"
command = """\
export GIT_CREDENTIALS=https://$GITHUB_TOKEN:@github.com; \
node_modules/.bin/antora --fetch --generator=@antora/site-generator-ms --redirect-facility=netlify ../antora-playbook.yml\
"""

[build.environment]
NODE_VERSION = "10"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.deploy-preview]
command = """\
export GIT_CREDENTIALS=https://$GITHUB_TOKEN:@github.com; \
node_modules/.bin/antora --fetch --generator=@antora/site-generator-ms --redirect-facility=netlify --url $DEPLOY_PRIME_URL ../antora-playbook.yml\
"""

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
