[build]
base = "netlify/"
publish = "public/"
command = "sed -i \"s;git@github.com:;https://$GITHUB_TOKEN:x-oauth-basic@github.com/;g\" ../staging-site.yml && node_modules/.bin/antora --pull --redirect-facility=netlify ../staging-site.yml"

[build.environment]
NODE_VERSION = "8"
BUILD_ONLY = "true"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.production.environment]
ALGOLIA_API_KEY = "6e7248a6d21038512a92145e9b903757"
ALGOLIA_APP_ID = "E80Q5UHPOS"
ALGOLIA_INDEX_NAME = "couchbase-docs-next"
FEEDBACK_BUTTON = "true"

[context.deploy-preview]
command = "sed -i \"s;git@github.com:;https://$GITHUB_TOKEN:x-oauth-basic@github.com/;g\" ../staging-site.yml && node_modules/.bin/antora --url $DEPLOY_PRIME_URL --pull --redirect-facility=netlify ../staging-site.yml"

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
