[build]
base = "netlify/"
publish = "public/"
"""

[build.environment]
NODE_VERSION = "10"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.deploy-preview]
command = """\
node_modules/.bin/antora --fetch --generator=@antora/xref-validator ../antora-playbook.yml || true; \
node_modules/.bin/antora --redirect-facility=netlify --url $DEPLOY_PRIME_URL ../antora-playbook.yml \
"""

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
