[build]
  base = "netlify/"
  publish = "public/"
  command = "sed -i \"s;git@github.com:;https://$GITHUB_TOKEN:x-oauth-basic@github.com/;g\" ../site.yml && node_modules/.bin/antora --url https://docs-staging.couchbase.com --pull --redirect-facility=netlify ../site.yml && sed -i \"s;^/index.html ;/ ;\" ../public/_redirects"

[build.environment]
  NODE_VERSION = "8"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.production.environment]
  ALGOLIA_API_KEY = "ea9d60816cf2bd04472648bfb287fde1"
  ALGOLIA_INDEX_NAME = "couchbase"
  FEEDBACK_BUTTON = "true"

[context.deploy-preview]
  command = "sed -i \"s;git@github.com:;https://$GITHUB_TOKEN:x-oauth-basic@github.com/;g\" ../site.yml && node_modules/.bin/antora --url $DEPLOY_PRIME_URL --pull --redirect-facility=netlify ../site.yml && sed -i \"s;^/index.html ;/ ;\" ../public/_redirects"

[[headers]]
  for = "/_/font/*"
  [headers.values]
    Cache-Control = "public,max-age=604800"
