site:
  title: Couchbase Docs (Review Site)
  start_page: operator:ROOT:overview.adoc
content:
  sources:
  - url: git@github.com:cb-docs-review-space/couchbase-operator.git
    branches: v*
    start_path: docs/user
  - url: git@github.com:cb-docs-review-space/asterix-opt.git
    branches: v*
    start_path: cbas/doc-publish
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./public
