site:
  title: Couchbase Docs (Review Site)
  start_page: operator:ROOT:overview.adoc
content:
  sources:
  - url: git@github.com:cb-docs-review-space/couchbase-operator.git
    branches: v*
    start_path: docs/user
  - url: git@github.com:cb-docs-review-space/asterix-opt.git
    branches: v*
    start_path: cbas/doc-publish
  - url: https://github.com/cb-docs-review-space/couchbase-cli.git
    branches: v*
    start_path: docs
  - url: git@github.com:cb-docs-review-space/backup.git
    branches: v*
    start_path: docs
  # server-docs is currently last so nav key wins
  - url: git@github.com:cb-docs-review-space/couchbase-server-docs.git
    branches: v*
asciidoc:
  extensions:
  - ./lib/inline-man-macro.js
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./public
