site:
  title: Couchbase Docs (Review Site)
  url: https://docs-staging.couchbase.com
  #start_page: server:introduction:intro.adoc
  start_page: home::index.adoc
content:
  branches: v*
  sources:
  - url: git@github.com:couchbase/docs-site.git
    branches: master
    start_path: home
  - url: git@github.com:couchbase/couchbase-operator.git
    branches: [beta2, master]
    start_path: docs/user
  - url: git@github.com:couchbase/docs-analytics.git
    branches: [1.0.x]
  - url: https://github.com/cb-docs-review-space/couchbase-cli.git
    start_path: docs
  - url: git@github.com:cb-docs-review-space/backup.git
    start_path: docs
  # server-docs is currently after other server repos so nav key wins
  - url: git@github.com:couchbase/docs-server.git
  - url: https://github.com/cb-docs-review-space/docs-sdk-c.git
  - url: https://github.com/cb-docs-review-space/docs-sdk-dotnet.git
  - url: https://github.com/cb-docs-review-space/docs-sdk-go.git
  - url: https://github.com/cb-docs-review-space/docs-sdk-java.git
  - url: https://github.com/cb-docs-review-space/docs-sdk-nodejs.git
  - url: https://github.com/cb-docs-review-space/docs-sdk-php.git
  - url: https://github.com/cb-docs-review-space/docs-sdk-python.git
asciidoc:
  attributes:
    experimental: ''
    toc: ~
    xrefstyle: short
  extensions:
  - ./lib/inline-man-macro.js
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/v22/ui-bundle.zip
output:
  dir: ./public
