site:
  title: Couchbase Docs (Review Site)
  url: https://docs-staging.couchbase.com
  start_page: server:introduction:intro.adoc
content:
  sources:
  - url: git@github.com:couchbase/couchbase-operator.git
    branches: [beta2, master]
    start_path: docs/user
  - url: git@github.com:couchbase/docs-analytics.git
    branches: [1.0.x]
  - url: https://github.com/cb-docs-review-space/couchbase-cli.git
    branches: v*
    start_path: docs
  - url: git@github.com:cb-docs-review-space/backup.git
    branches: v*
    start_path: docs
  # server-docs is currently after other server repos so nav key wins
  - url: git@github.com:couchbase/docs-server.git
    branches: v*
asciidoc:
  attributes:
    experimental: ''
    toc: ~
    xrefstyle: short
  extensions:
  - ./lib/inline-man-macro.js
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/v8/ui-bundle.zip
output:
  dir: ./public
