site:
  title: Couchbase Docs (Review Site)
  start_page: server:introduction:intro.adoc
content:
  sources:
  - url: git@github.com:cb-docs-review-space/couchbase-operator.git
    branches: v*
    start_path: docs/user
  - url: https://github.com/cb-docs-review-space/cbas-doc-staging.git
    branches: v*
  - url: https://github.com/cb-docs-review-space/couchbase-cli.git
    branches: v*
    start_path: docs
  - url: git@github.com:cb-docs-review-space/backup.git
    branches: v*
    start_path: docs
  # server-docs is currently after other server repos so nav key wins
  - url: https://github.com/cb-docs-review-space/couchbase-server-docs.git
    branches: v*
asciidoc:
  extensions:
  - ./lib/inline-man-macro.js
ui:
  bundle:
    url: https://github.com/cb-docs-review-space/cb-docs-ui/releases/download/v11/ui-bundle.zip
output:
  dir: ./public
