[build]
publish = "public"
ignore = "false"

[build.environment]
CI = "true"
NODE_VERSION = "12"
NPM_FLAGS = "--no-optional"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.production]
command = """\
if [ -v GITHUB_TOKEN ]; then export GIT_CREDENTIALS=https://$GITHUB_TOKEN:@github.com; fi; \
node_modules/.bin/antora --fetch --redirect-facility=netlify --to-dir=public --url $DEPLOY_PRIME_URL ../antora-playbook.yml\
"""

[context.deploy-preview]
command = """\
if [ -v GITHUB_TOKEN ]; then export GIT_CREDENTIALS=https://$GITHUB_TOKEN:@github.com; else node ../scripts/remove-private-content-sources.js ../antora-playbook.yml; fi; \
node_modules/.bin/antora --fetch --redirect-facility=netlify --to-dir=public --url $DEPLOY_PRIME_URL ../antora-playbook.yml\
"""

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
